# Generated by Django 5.1.7 on 2025-04-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.service'),
        ),
    ]
